# Generated by Django 2.0.6 on 2018-07-14 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('I', 'International'), ('P', 'Professional'), ('S', 'Semi-Professional'), ('C', 'College')], max_length=1)),
                ('league', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('mascot', models.CharField(max_length=30, null=True)),
                ('home_stadium_name', models.CharField(max_length=50, null=True)),
                ('home_stadium_lat', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('home_stadium_lon', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('abbrev', models.CharField(max_length=5)),
                ('first_year', models.IntegerField(null=True)),
                ('titles', models.IntegerField()),
                ('sport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports50web.Sports')),
            ],
        ),
    ]
