# Generated by Django 2.0.6 on 2018-09-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0004_players_draft_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='football_passing_plays',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
