# Generated by Django 2.0.6 on 2018-09-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0005_auto_20180922_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='football_passing_plays',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='football_passing_plays',
            old_name='opponent_team_id',
            new_name='opponent_team',
        ),
        migrations.RenameField(
            model_name='football_passing_plays',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='football_passing_plays',
            old_name='sport_id',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='football_passing_plays',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='sport_id',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='sport_id',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='sport_id',
            new_name='sport',
        ),
    ]
