# Generated by Django 2.0.6 on 2018-09-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0006_auto_20180922_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='team_one_id',
            new_name='team_one',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='team_two_id',
            new_name='team_two',
        ),
    ]
