# Generated by Django 2.0.6 on 2019-06-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0008_auto_20190606_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadiums',
            name='years',
        ),
        migrations.AddField(
            model_name='stadiums',
            name='first_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stadiums',
            name='last_year',
            field=models.IntegerField(default=2050),
        ),
    ]
