# Generated by Django 2.0.6 on 2019-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0009_auto_20190606_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiums',
            name='super_bowl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadiums',
            name='super_bowl_year',
            field=models.IntegerField(null=True),
        ),
    ]
