# Generated by Django 2.0.6 on 2019-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0011_auto_20190606_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='logo',
            field=models.CharField(default='na', max_length=500),
            preserve_default=False,
        ),
    ]
