# Generated by Django 2.0.6 on 2019-06-13 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports50web', '0012_teams_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Rushing_Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField()),
                ('time', models.TimeField()),
                ('down', models.IntegerField()),
                ('to_go', models.IntegerField()),
                ('side_of_field', models.IntegerField(choices=[(0, '50 yeard line'), (1, 'own side of field'), (2, 'opponent side of field')])),
                ('yard_line', models.IntegerField()),
                ('team_points', models.IntegerField()),
                ('opponent_points', models.IntegerField()),
                ('description', models.CharField(max_length=1000, null=True)),
                ('yards', models.IntegerField()),
                ('epb', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('epa', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('diff', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('touchdown', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('declined', models.IntegerField()),
                ('fumble', models.IntegerField()),
                ('tackle_for_loss', models.IntegerField()),
                ('tackle', models.IntegerField()),
                ('guard', models.IntegerField()),
                ('end', models.IntegerField()),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('middle', models.IntegerField()),
                ('no_play', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports50web.GameLog')),
                ('opponent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_rushing', to='sports50web.Teams')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports50web.Players')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports50web.Sports')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rushing', to='sports50web.Teams')),
            ],
        ),
    ]
